name: CI/CD Pipeline for Service Discovery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t service-discovery .
        docker tag service-discovery:latest 326061183428.dkr.ecr.us-east-2.amazonaws.com/service-discovery:latest

    - name: Push Docker image to ECR
      run: |
        docker push 326061183428.dkr.ecr.us-east-2.amazonaws.com/service-discovery:latest
